title: Yuvita Andriani Kusumadewi # your name (or website title) here
logo: "/images/K1320085.jpg?raw=true" # your photo (or logo) here
  <p align="center">
  <a "CV [Yuvita Andriani Kusumadewi].pdf?raw=true">Resume</a> |
  <a href="https://www.linkedin.com/in/yuvita-andriani-kusumadewi-b037341a7/">LinkedIn</a> |
  <a href="https://github.com/yuvita13">GitHub</a> 
  </p>
description: > # your text below (remove <br> elements if you don't need line breaks)
  As a student who loves mathematics and is interested in teaching, I started to open the gates of my dreams by studying at the Department of Mathematics Education at Universitas Sebelas Maret. I like teaching, especially teaching math. I'm a fast learner and a highly enthusiastic person. Finding new experiences and skills is my way to improve myself. I also have an interest in the technology and design field. I'm starting to study in that field. 
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
