title: Yuvita Andriani Kusumadewi 
logo: "/images/yuvita.png?raw=true"
description: >
  <p style="text-align:center;">
  <a href="CV [Yuvita Andriani Kusumadewi].pdf?raw=true">Resume</a> |
  <a href="https://www.linkedin.com/in/yuvita-andriani-kusumadewi-b037341a7/">LinkedIn</a> |
  <a href="https://github.com/yuvita13">GitHub</a>
  </p>
  <br>
  <p style="text-align:justify;">
  As a student who loves mathematics and is interested in teaching, I started to open the gates of my dreams by studying at the Department of Mathematics Education at Universitas Sebelas Maret. 
  <br><br>
  I like teaching, especially teaching math. I'm a fast learner and a highly enthusiastic person. Finding new experiences and skills is my way to improve myself. 
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
